#!/bin/bash

# Squeezebox Server CPAN modules are originally from here:
# http://svn.slimdevices.com/repos/slim/vendor/src

DIR=$1
DEST_HOST=$2

cd $DIR
for FILE in *.gz; do
	scp -i ~/.ssh/$DEST_HOST $FILE root@$DEST_HOST:/usr/portage/distfiles/$FILE
done
